songbeard_show_list:
    pattern:  /
    defaults: { _controller: SongbeardShowBundle:ShowManagement:list }

songbeard_show_add:
    pattern:  /add
    defaults: { _controller: SongbeardShowBundle:ShowManagement:add }

songbeard_show_search:
    pattern:  /search.{_format}
    defaults: { _controller: SongbeardShowBundle:ShowRest:search, _format: ~ }
    requirements:
        _method: GET