songbeard_songbeard:
    resource: "@SongbeardSongbeardBundle/Controller/"
    type:     annotation
    prefix:   /

songbeard_show:
    resource: "@SongbeardShowBundle/Resources/config/routing.yml"
    prefix:   /shows/

