<?php

namespace Songbeard\SongbeardBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TvShowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TvShowRepository extends EntityRepository
{
}
